version: '3'

services:
  app:
    container_name: machine
    restart: unless-stopped
    build: ./docker
    image: blog-dev
    volumes:
      - ${PWD}/www:/var/www
    ports:
      - 80:80
    networks:
      - machine
    env_file:
      - .env

  mysql:
    container_name: machine.mysql
    restart: unless-stopped
    image: mariadb
    networks: 
      - machine
    env_file:
      - .env

networks: 
  machine:
    driver: bridge